### ISSUE TITLE
Wanted Wake-Words

### ISSUE THREAD

**Issue by fwartner** [fwartner/home-assistant-wakewords-collection#1]
Comment your wanted wake-words below this comment.

**Comment by kevvar** [comment]
Bro, this is awesome. I don't work with github usually, how can I upload some wake words to share? Maybe I can send you a google drive link with some wake words.

**Comment by fwartner** [comment]
Sure! Feel free to send me the link and i'm gonna add it to the repository!

**Comment by kevvar** [comment]
Great, here you go https://drive.google.com/drive/folders/1623ms9Uw7uj-5x1nH9Dwyp4XBW4w_hzJ
I'll be adding others words on the go

**Comment by fwartner** [comment]
Added the first ones! :)

**Comment by brewston** [comment]
Here's mine https://github.com/brewston/Homeaassistant-voiceintents/blob/main/edna.tflite

**Comment by kevvar** [comment]
Built today:

Kreitos, (yes, Kratos from the God of War game) disregard the writing, just spelling things
Mr. Whick (from the universe of John Wick)
Winston (from the universe of John Wick)
Maar vin, It sounds "Marvin"
Ok Jarvis
Hey Honey
Mr. Anderson
Scarlett

**Comment by davefx** [comment]
I'm having some problems building new wake words.
I'd like to build "Hola, Casita", used in the Encanto movie.
To mimic the Spanish pronunciation, the string `oh laakaasee dah` sounds very similar to what it should sound in Spanish.

**Comment by starsoccer** [comment]
Barclay from Tom Swift, https://nancydrew.fandom.com/wiki/Barclay

**Comment by kevvar** [comment]
@davefx I was trying to generate the wake word 3 times, each one gave me an error, checking the log it happens that the combination of letters causes an error in the generation of the model when the script looks for the pronunciations in the dictionaries and throws an error when executing the third training routine.

Today:

Ok Nabu
Ronaldo
Hey Homer
Skynet
Santana
Home Assistant
Barclay

@fwartner Could you please edit the names Kreitos to Kratos and Maar_vin to Marvin for a better understanding? I didn't think about it when uploaded

**Comment by fwartner** [comment]
> @fwartner Could you please edit the names Kreitos to Kratos and Maar_vin to Marvin for a better understanding? I didn't think about it when uploaded

Will do later when i'm done with meetings.

**Comment by off112a** [comment]
I would love to have "Janet" as a wake word. It's from the TV serie The good place.

**Comment by kevvar** [comment]
> I would love to have "Janet" as a wake word. It's from the TV serie The good place.

Done, find it in the google drive link above and the repo when it'll be updated

**Comment by fwartner** [comment]
Done :)

**Comment by sparkydave1981** [comment]
I know we already have 'hey Jarvis' but I'd like just 'Jarvis'.

**Comment by itnassol** [comment]
Here is Ada if you want it.

https://github.com/itnassol/Ada

**Comment by thewolf-oz** [comment]
Have added a couple more and raised pull request - https://github.com/fwartner/home-assistant-wakewords-collection/pull/5

I'm having some troubles doing more, it keeps failing but I have a few I'm considering

**Comment by smartmatic** [comment]
Great idea, here is my contribution :-) Nothing special but still not yet listed in your collection.
https://drive.google.com/drive/folders/14viEMHMMgXi0aLMGLDWfNH2hwRpoiEtX?usp=sharing

**Comment by bluenazgul** [comment]
I Wish there would be wakewords for the German Community, sadly the Tool right now only Supports English

**Comment by smartmatic** [comment]
May be we can start collecting german wake words in a second issue until its possible to generate the files via collab?

**Comment by faduchesne** [comment]
thx for the list but I search for French wake word ;)

**Comment by smartmatic** [comment]
So we need a multilanguage sorted wake word list 😀Do somebody know when wake words can be translated to other languages?

**Comment by ijustlikeit** [comment]
ok boss

https://github.com/ijustlikeit/wake-words/blob/main/ok_boss.tflite

**Comment by kevvar** [comment]
> So we need a multilanguage sorted wake word list 😀Do somebody know when wake words can be translated to other languages?

Maybe on the next chapters

**Comment by kevvar** [comment]
Added new ones to drive https://drive.google.com/drive/folders/1623ms9Uw7uj-5x1nH9Dwyp4XBW4w_hzJ?usp=sharing

**Comment by pcwii** [comment]
Any chance I could get you to make 'kelsey' I managed to make a low sample model but things keep crashing when I try a high sample model. 'Kelsey' was an imaginary friend of my young daughter,  now that she's older she finds it neet to have kelsey talk back.

**Comment by fwartner** [comment]
Added new ones.

**Comment by fwartner** [comment]
> Any chance I could get you to make 'kelsey' I managed to make a low sample model but things keep crashing when I try a high sample model. 'Kelsey' was an imaginary friend of my young daughter, now that she's older she finds it neet to have kelsey talk back.

I am pretty sure that someone will make one. Since the collection is growing and growing, I am thinking about creating a website for this too where you cane create requests for new wake-words.

**Comment by kevvar** [comment]
> Any chance I could get you to make 'kelsey' I managed to make a low sample model but things keep crashing when I try a high sample model. 'Kelsey' was an imaginary friend of my young daughter, now that she's older she finds it neet to have kelsey talk back.

Done https://drive.google.com/drive/folders/1623ms9Uw7uj-5x1nH9Dwyp4XBW4w_hzJ

**Comment by jimbob1001** [comment]
Would love Hey Artoo

**Comment by fwartner** [comment]
> > Any chance I could get you to make 'kelsey' I managed to make a low sample model but things keep crashing when I try a high sample model. 'Kelsey' was an imaginary friend of my young daughter, now that she's older she finds it neet to have kelsey talk back.
> 
> Done https://drive.google.com/drive/folders/1623ms9Uw7uj-5x1nH9Dwyp4XBW4w_hzJ

Already implemented.

**Comment by ijustlikeit** [comment]
hey home free

https://github.com/ijustlikeit/wake-words/blob/main/hey-home-free.tflite)](https://github.com/ijustlikeit/wake-words/blob/main/hey_home_free.tflite

**Comment by Jacksaur** [comment]
Seeing as this Issue has been closed, does that mean new Wake Word suggestions are no longer being taken anymore?

Just in case they are, I'd love to have "Moon" (Rain World reference) and "Anubis" available!

**Comment by fwartner** [comment]
Sure.. They are open.. :)

**Comment by jacobkaad01** [comment]
Hey Genie and Ok Genie

**Comment by jacobkaad01** [comment]
> Hey Genie and Ok Genie

And maybe just “Genie” by itself?

**Comment by sayam93** [comment]
Could someone please do a siri? The one I made using google colab doesn't seem to work...

**Comment by Greylinux** [comment]
I'm really surprised Cortana hasn't been requested , is there a reason behind that ?
